---
abstract: 'HTTP Body Parser'
author:
  - 'Christian Hansen, C<chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Body
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  File::Temp: 0.14
  HTTP::Headers: 0
  IO::File: 1.14
resources:
  license: http://dev.perl.org/licenses/
version: 1.07
